// <auto-generated />
namespace vkrS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class result2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(result2));
        
        string IMigrationMetadata.Id
        {
            get { return "202005161032150_result2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
