// <auto-generated />
namespace vkrS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class result1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(result1));
        
        string IMigrationMetadata.Id
        {
            get { return "202005161024562_result1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
